databases:
  - name: mairie_tchad
    databaseName: mairie_tchad
    user: mairie_user

services:
  - type: web
    name: mairie-tchad
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: mairie_tchad
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mairie_tchad
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mairie_tchad
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mairie_tchad
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mairie_tchad
          property: password